// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC8566e17DecodeGithubComGoParkMailRu20211YSNPInternalAppModels(in *jlexer.Lexer, out *WSMessageResp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = int(in.Int())
		case "type":
			out.Type = string(in.String())
		case "data":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Data).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC8566e17EncodeGithubComGoParkMailRu20211YSNPInternalAppModels(out *jwriter.Writer, in WSMessageResp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Status))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WSMessageResp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC8566e17EncodeGithubComGoParkMailRu20211YSNPInternalAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WSMessageResp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC8566e17EncodeGithubComGoParkMailRu20211YSNPInternalAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WSMessageResp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC8566e17DecodeGithubComGoParkMailRu20211YSNPInternalAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WSMessageResp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC8566e17DecodeGithubComGoParkMailRu20211YSNPInternalAppModels(l, v)
}
func easyjsonC8566e17DecodeGithubComGoParkMailRu20211YSNPInternalAppModels1(in *jlexer.Lexer, out *WSMessageReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "data":
			(out.Data).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC8566e17EncodeGithubComGoParkMailRu20211YSNPInternalAppModels1(out *jwriter.Writer, in WSMessageReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		(in.Data).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WSMessageReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC8566e17EncodeGithubComGoParkMailRu20211YSNPInternalAppModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WSMessageReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC8566e17EncodeGithubComGoParkMailRu20211YSNPInternalAppModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WSMessageReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC8566e17DecodeGithubComGoParkMailRu20211YSNPInternalAppModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WSMessageReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC8566e17DecodeGithubComGoParkMailRu20211YSNPInternalAppModels1(l, v)
}
func easyjsonC8566e17DecodeGithubComGoParkMailRu20211YSNPInternalAppModels2(in *jlexer.Lexer, out *CustomData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "request_data":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.RequestData).UnmarshalJSON(data))
			}
		case "type_data":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.TypeData).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC8566e17EncodeGithubComGoParkMailRu20211YSNPInternalAppModels2(out *jwriter.Writer, in CustomData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_data\":"
		out.RawString(prefix[1:])
		out.Raw((in.RequestData).MarshalJSON())
	}
	{
		const prefix string = ",\"type_data\":"
		out.RawString(prefix)
		out.Raw((in.TypeData).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CustomData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC8566e17EncodeGithubComGoParkMailRu20211YSNPInternalAppModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CustomData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC8566e17EncodeGithubComGoParkMailRu20211YSNPInternalAppModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CustomData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC8566e17DecodeGithubComGoParkMailRu20211YSNPInternalAppModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CustomData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC8566e17DecodeGithubComGoParkMailRu20211YSNPInternalAppModels2(l, v)
}
